homepage_title: Rainbond 文档中心
site_title: Rainbond

url: "https://www.rainbond.com"
baseurl: "/docs"

plugins:
- jekyll-sitemap
- jekyll-last-modified-at

highlighter: rouge
markdown: redcarpet

redcarpet:
  extensions:
  - disable_indented_code_blocks
  - no_intra_emphasis
  - tables
  - with_toc_data

versions:
  stable: v3.4

release_info:
  v3.4:
    version: v3.4.1
    build_time: 2017/09/14 15:13:51
    start_time: 2017-09-14 13:33:22.046027038 -0400 EDT

exclude: ["ci", "vendor"]

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
