homepage_title: Rainbond 文档中心
site_title: Rainbond

url: "https://www.rainbond.com"
baseurl: "/docs"

plugins:
- jekyll-sitemap

highlighter: rouge
markdown: redcarpet

redcarpet:
  extensions:
  - disable_indented_code_blocks
  - no_intra_emphasis
  - tables
  - with_toc_data

versions:
  v3.4: v3.4
  v3.5: v3.5
  v3.6: v3.6
  stable: v3.7

release_info:
  v3.4:
    version: v3.4.2
    build_time: 2017/12/25 16:35:45
    start_time: 2017-12-25 19:33:22.046027038 +800 CST
  v3.5:
    name: v3.5.2
    version: v3.5.2
    build_time: 2018/03/26 16:35:45
    start_time: 2018-03-26 19:33:22.046027038 +800 CST
  v3.6:
    name: v3.6.1
    version: v3.6.1
    build_time: 2018/07/19 16:35:45
    start_time: 2018/07/19 19:33:22.046027038 +800 CST  
  v3.7:
    name: v3.7.0
    version: v3.7.0
    build_time: 2018/08/15 10:13:27
    start_time: 2018/08/15 10:10:14.012472125 +800 CST 

exclude: ["ci", "vendor"]

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

algolia:
   application_id: JW03QS46UU
   index_name: rainbond
