---
baseurl: "https://www.rainbond.com/docs/"
languageCode: "zh-cn"
DefaultContentLanguage: "zh-cn"
title: "Rainbond-企业应用云操作系统，云原生企业业务中台基座"
theme: "rainbond"
baseURL: ""
canonifyURLs: true
params:
  editURL: "https://github.com/goodrain/rainbond-docs/edit/master/content/"
  showVisitedLinks: true
  disableShortcutsTitle: false
  description: "Rainbond是以应用为中心，面向云原生的企业应用操作系统，将企业数字资产抽象为应用模型（Rainbond Application Model），并通过容器化环境、敏捷DevOps、微服务架构、组件制品库、Serverless部署、底层资源自动化运维等核心技术，通过搭建数字中台、加速前台业务需求响应，帮助企业获得面向未来的创新能力和竞争力。"
  keywords: "视频教程，好雨, goodrain, Rainbond, 云帮, 以应用为中心, serverless, PaaS, SaaS, Kubernetes, 微服务架构, servicemesh, DevOps, CI/CD, 高效运维, 云原生, 公有云, 私有云, 混合云, 应用交付, 微服务, 容器云, 容器云平台, 容器云服务, 镜像构建, 源码构建, 云原生应用, 微服务, 微服务平台, springcloud微服务架构, service mesh, 服务网格, 微服务设计, sidecar, 行业云, 开发云, 智慧云, 云计算解决方案"
outputs:
  home: 
    - HTML
    - RSS 
    - JSON
    - Algolia
outputFormats:
  Algolia:
    baseName: "algolia"
    isPlainText: true
    mediaType: "application/json"
    notAlternative: true