---
baseurl: 'http://v5.3-doc.rainbond.com/docs/'
languageCode: 'zh-cn'
DefaultContentLanguage: 'zh-cn'
title: 'Rainbond-云原生且易用的应用管理平台'
theme: 'rainbond'
baseURL: ''
canonifyURLs: true
params:
  version: 20210221
  editURL: 'https://github.com/goodrain/rainbond-docs/edit/master/content/'
  issuesURL: 'https://github.com/goodrain/rainbond-docs/issues/new'
  showVisitedLinks: true
  disableShortcutsTitle: false
  description: '云原生应用交付的最佳实践，简单易用。专注于以应用为中心的理念。赋能企业搭建云原生开发云、云原生交付云。'
  keywords: '云原生,云原生应用,视频教程,好雨, goodrain, Rainbond, 云帮, 以应用为中心, serverless, PaaS, SaaS, Kubernetes, 微服务架构, servicemesh, DevOps, CI/CD, 高效运维, 云原生, 公有云, 私有云, 混合云, 应用交付, 微服务, 容器云, 容器云平台, 容器云服务, 镜像构建, 源码构建, 云原生应用, 微服务, 微服务平台, springcloud微服务架构, service mesh, 服务网格, 微服务设计, sidecar, 行业云, 开发云, 智慧云, 云计算解决方案'
  dashboard:
    recommended:
      - title: 应用开发
        docs:
          - title: 使用StatefulSet部署应用
            url: /docs/practices/app-dev/statefulset
          - title: 用 Dockerfile 构建运行应用
            url: /docs/practices/app-dev/build_by_dockerfile
          - title: 部署Vue、React前端项目
            url: /docs/practices/app-dev/build-react-and-vue
          - title: Vue、React项目调用后端接口
            url: /docs/practices/app-dev/connect-api
          - title: 部署 API-Gateway
            url: /docs/get-start/best-practices/work_with_kong
          - title: 组件依赖端口冲突处理
            url: /docs/practices/app-dev/port-conflict
          - title: 应用复制快速搭建开发环境
            url: /docs/user-manual/component-dev/app_copy/
          - title: 部署自动初始化Schema的数据库
            url: /docs/practices/app-dev/auto-schema
          - title: 部署Spark Standalone集群
            url: /docs/practices/app-dev/deploy-spark
          - title: 服务间通信,端口别名的使用
            url: /docs/practices/app-dev/port-alias
          - title: 部署SpringCloud微服务
            url: /docs/practices/app-dev/spring-cloud-case/
          - title: 整合Git仓库快速部署组件
            url: /docs/practices/app-dev/work_with_git/

      - title: 应用运维
        docs:
          - title: 业务自定义监控
            url: /docs/user-manual/component-op/custom-monitor/
          - title: Java类组件监控与链路追踪
            url: /docs/get-start/best-practices/work_with_apm/
          - title: 为组件添加配置文件
            url: /docs/get-start/best-practices/config_file/
          - title: 组件日志发送到阿里云
            url: /docs/get-start/best-practices/collect_log/
          - title: 应用级配置组管理
            url: /docs/user-manual/app-manage/config-group/
          - title: 实现A/B测试
            url: /docs/practices/app-dev/ab_testing/
          - title: 实现一键上线/回滚
            url: /docs/practices/app-dev/update-rollback/
          - title: 滚动发布，灰度发布及蓝绿发布
            url: /docs/practices/app-dev/app_publishing/
          - title: Java类组件自定义监控
            url: /docs/practices/app-dev/java-exporter/
          - title: 组件日志发送到ELK
            url: /docs/practices/app-dev/work_with_elk/
      - title: 应用交付
        docs:
      - title: 集群管理
        docs:
          - title: 新增集群
            url: /docs/user-operations/cluster-manage/add-cluster/
          - title: 集群基础管理
            url: /docs/user-operations/cluster-manage/manage-cluster/
          - title: Rainbond系统运维
            url: /docs/user-operations/management/component-op/
          - title: 监控报警部署
            url: /docs/user-operations/monitor/monitoring-alarm-configuration/
          - title: 存储系统扩展对接
            url: /docs/user-operations/storage/
          - title: 重新指定Gateway节点
            url: /docs/practices/operator/gateway-node/
    faqs:
      - q: Rainbond 是否开源
        a: 当然，Rainbond是一个完整开源的以企业云原生应用开发、架构、运维、共享、交付为核心的Kubernetes多云赋能平台，企业级支持的国产开源项目，订阅企业服务可以解锁更多便捷功能体验和获得专业的支持。
      - q: Rainbond 与 Rancher 的区别
        a: Rancher，Kubernetes生态中成功的开源项目，其定位“Run Kubernetes Everywhere”，Rancher可以帮助我们快速搭建Kubernetes集群并提供集群资源很好的管理体系。Rainbond定位“企业应用全生命周期管理“，可以这么认为Rainbond在Rancher之上的维度，用Rancher更好的管理Kubernetes，用Rainbond更好、更方便的使用Kubernetes。因此Rainbond与Rancher甚至可以并存，各司其职。
      - q: Rainbond 支持管理各类公有云资源吗
        a: Rainbond从5.2版本开始适用于公有云资源以应用为中心的统一管理，Rainbond Cloud版本已支持对阿里云资源的对接、逐步支持aws、华为云等。资源对接包括Kubernetes集群、数据库、存储等
      - q: Rainbond 支持多云管理吗
        a: 当然，Rainbond支持便捷的管理多云应用。
  video:
    news:
      title: 最新上线视频
      items:
        - title: 【Rainbond 社区分享回放】5.2.2 升级到 5.3.0 实践
          bilibili: https://www.bilibili.com/video/BV1Rv411h7Gx/
          src: //player.bilibili.com/player.html?aid=247098830&bvid=BV1Rv411h7Gx&cid=309105912&page=1
          default: true
        - title: 【Rainbond 社区分享回放】应用全方位监控、可视化实践
          bilibili: https://www.bilibili.com/video/BV11A411K7Pd/
          src: //player.bilibili.com/player.html?aid=331943093&bvid=BV11A411K7Pd&cid=306022663&page=1
        - title: 【Rainbond 社区分享回放】Rainbond 5.3 版本架构变更与集群安装方式变更讲解和演示
          bilibili: https://www.bilibili.com/video/BV1di4y1T72M/
          src: //player.bilibili.com/player.html?aid=544440225&bvid=BV1di4y1T72M&cid=305156874&page=1
        - title: Rainbond线上沙龙-组件日志对接到阿里云日志服务
          src: //player.bilibili.com/player.html?aid=883344773&bvid=BV1yK4y1t7cY&cid=195923930&page=1
          bilibili: https://www.bilibili.com/video/BV1yK4y1t7cY/
          doc: /docs/get-start/best-practices/collect_log/
        - title: Rainbond结合Kong实现API-Gateway
          src: //player.bilibili.com/player.html?aid=200652814&bvid=BV1zz411q7m7&cid=193486378&page=1
          bilibili: https://www.bilibili.com/video/BV1zz411q7m7/
          doc: /docs/user-manual/best-practices/work_with_kong/
        - title: Rancher安装Rainbond, 并做应用部署的简单对比演示
          src: //player.bilibili.com/player.html?aid=625675438&bvid=BV1kt4y117Gu&cid=191668386&page=1
          bilibili: https://www.bilibili.com/video/BV1kt4y117Gu/
        - title: 配置服务请求速率限制
          src: //player.bilibili.com/player.html?aid=540728010&bvid=BV1ai4y14718&cid=193184140&page=1
          bilibili: https://www.bilibili.com/video/BV1ai4y14718/
          doc: /docs/user-manual/architecture/rate-limiting/
        - title: Rainbond 应用复制-快速搭建开发环境
          src: //player.bilibili.com/player.html?aid=668179307&bvid=BV1da4y1i7tQ&cid=190877377&page=1
          bilibili: https://www.bilibili.com/video/BV1da4y1i7tQ
          doc: /docs/user-manual/component-dev/app_copy/
        - title: 基于应用市场的应用SaaS化交付流程演示
          src: //player.bilibili.com/player.html?aid=968145936&bvid=BV1xp4y1Q7CX&cid=190508594&page=1
          bilibili: https://www.bilibili.com/video/BV1xp4y1Q7CX
        - title: Rainbond配置域名访问组件
          src: //player.bilibili.com/player.html?aid=200637879&bvid=BV1Wz411q7Rm&cid=190491579&page=1
          bilibili: https://www.bilibili.com/video/BV1Wz411q7Rm
          doc: /docs/user-manual/gateway/domain/
        - title: Rainbond 组件间通信设置操作演示
          bilibili: https://www.bilibili.com/video/BV1qZ4y1s7nH
          src: //player.bilibili.com/player.html?aid=370629782&bvid=BV1qZ4y1s7nH&cid=190486373&page=1
        - title: 基于Rainbond实现企业DevOps全流程体验
          pdf: https://grstatic.oss-cn-shanghai.aliyuncs.com/mp4/ppt/%E5%9F%BA%E4%BA%8ERainbond%E5%AE%9E%E7%8E%B0DevOps%E5%85%A8%E6%B5%81%E7%A8%8B.pdf
          src: //player.bilibili.com/player.html?aid=667994901&bvid=BV1Ua4y1v7ob&cid=185062763&page=1
          bilibili: https://www.bilibili.com/video/BV1Ua4y1v7ob/
        - title: 3分钟速览RainbondCloud对接阿里云资源
          src: //player.bilibili.com/player.html?aid=837884755&bvid=BV1hg4y1z7WC&cid=184669028&page=1
          bilibili: https://www.bilibili.com/video/BV1hg4y1z7WC
        - title: Rainbond V5.2.0 BETA1 解读
          src: //player.bilibili.com/player.html?aid=89807690&cid=153384707&page=1
          bilibili: https://www.bilibili.com/video/av89807690/
          pdf: https://grstatic.oss-cn-shanghai.aliyuncs.com/mp4/ppt/Rainbond%205.2%20beta1%20.pdf
    v5.1:
      title: V5.1版本参考视频
      description: V5.1版本集群安装相关参考视频已不适用于V5.2版本
      items:
        - title: Rainbond开源两周年线上沙龙
          src: //player.bilibili.com/player.html?aid=79059089&cid=135299440&page=1
          bilibili: https://www.bilibili.com/video/av79059089?p=1
        - title: Jenkins Pipeline 对接Rainbond用法培训
          src: //player.bilibili.com/player.html?aid=54042295&cid=94538571&page=1
          bilibili: https://www.bilibili.com/video/av54042295/
        - title: SpringCloud微服务架构应用部署到Rainbond用法培训
          src: //player.bilibili.com/player.html?aid=54682957&cid=95656299&page=1
          bilibili: https://www.bilibili.com/video/av54682957/
        - title: Eureka集群部署，SpringCloud微服务架构升级培训
          bilibili: https://www.bilibili.com/video/av55425832/
          src: //player.bilibili.com/player.html?aid=55425832&cid=96911217&page=1
        - title: Java生态的微服务无侵入链路追踪
          bilibili: https://www.bilibili.com/video/av56157222/
          src: //player.bilibili.com/player.html?aid=56157222&cid=98157334&page=1
          pdf: https://grstatic.oss-cn-shanghai.aliyuncs.com/mp4/ppt/Java%E7%94%9F%E6%80%81%E5%BE%AE%E6%9C%8D%E5%8A%A1%E6%97%A0%E4%BE%B5%E5%85%A5%E9%93%BE%E8%B7%AF%E8%BF%BD%E8%B8%AA.pdf
        - title: 如何将企业应用制作为SaaS化应用并打通开发测试交付链路
          bilibili: https://www.bilibili.com/video/av56969937/
          src: //player.bilibili.com/player.html?aid=56969937&cid=99503149&page=1
          pdf: https://grstatic.oss-cn-shanghai.aliyuncs.com/mp4/ppt/%E7%BA%BF%E4%B8%8A%E5%9F%B9%E8%AE%AD%E7%AC%AC%E4%BA%94%E6%9C%9FRainbond%E5%BA%94%E7%94%A8%E5%B8%82%E5%9C%BA%E8%A7%A3%E8%AF%BB.pdf
        - title: 滚动、蓝绿、灰度如何在Rainbond实现
          src: //player.bilibili.com/player.html?aid=57780580&cid=100850214&page=1
          pdf: https://grstatic.oss-cn-shanghai.aliyuncs.com/mp4/ppt/%E7%BA%BF%E4%B8%8A%E5%9F%B9%E8%AE%AD%E7%AC%AC%E5%85%AD%E6%9C%9F%E5%9F%BA%E4%BA%8Erainbond%E5%AE%9E%E7%8E%B0%E4%B8%89%E7%A7%8D%E5%BE%AE%E6%9C%8D%E5%8A%A1%E5%8F%91%E5%B8%83%E6%96%B9%E5%BC%8F%20.pdf
          bilibili: https://www.bilibili.com/video/av57780580/
        - title: 服务熔断和全局限流如何在Rainbond实现
          bilibili: https://www.bilibili.com/video/av60657760/
          src: //player.bilibili.com/player.html?aid=60657760&cid=105575102&page=1
          pdf: https://grstatic.oss-cn-shanghai.aliyuncs.com/mp4/ppt/%E7%BA%BF%E4%B8%8A%E5%9F%B9%E8%AE%AD%E7%AC%AC%E4%B8%83%E6%9C%9F%E5%9F%BA%E4%BA%8ERainbond%E5%AE%9E%E7%8E%B0%E6%9C%8D%E5%8A%A1%E7%86%94%E6%96%AD%E5%92%8C%E5%85%A8%E5%B1%80%E9%99%90%E6%B5%81.pdf
        - title: Rainbond日志管理与插件制作教程
          src: //player.bilibili.com/player.html?aid=61677518&cid=107266444&page=1
          bilibili: https://www.bilibili.com/video/av61677518/
          pdf: https://grstatic.oss-cn-shanghai.aliyuncs.com/mp4/ppt/Rainbond%E6%9C%8D%E5%8A%A1%E6%97%A5%E5%BF%97%E7%AE%A1%E7%90%86.pdf
        - title: Rainbond安装与运维原理解读
          src: //player.bilibili.com/player.html?aid=62878710&cid=109233154&page=1
          bilibili: https://www.bilibili.com/video/av62878710/
          pdf: https://grstatic.oss-cn-shanghai.aliyuncs.com/mp4/ppt/Rainbond%E5%AE%89%E8%A3%85%E4%B8%8E%E8%BF%90%E7%BB%B4%E5%8E%9F%E7%90%86%E8%A7%A3%E8%AF%BB.pdf
        - title: Rainbond高可用集群搭建
          bilibili: https://www.bilibili.com/video/av63784929/
          src: //player.bilibili.com/player.html?aid=63784929&cid=110739423&page=1
        - title: Rainbond应用构建、拼装、安装与升级流程演示
          bilibili: https://www.bilibili.com/video/av78830420/
          src: //player.bilibili.com/player.html?aid=78830420&cid=134888098&page=1
  users:
    - title: 京东方科技集团股份有限公司
      logo: images/users/boe.jpg
      description: 使用 Rainbond 2年，服务 100+ 开发者和 40 多个业务系统研发和交付。
    - title: 中国煤炭科工集团
      logo: images/users/meike.png
      description: 使用 Rainbond 1年，搭建了煤炭行业云基础平台，统一管理各类工业互联网应用。
    - title: 北控软件
      logo: images/users/bkrj.jpg
      description: 使用 Rainbond 3年，支撑开发者进行高效的应用研发和交付。
    - title: 中公高科
      logo: images/users/zggk.jpg
      description: 使用 Rainbond 3年
    - title: 青椒课堂
      logo: https://cdn.qingjiao.pub/20200814/img/logo_primary.6426014d.png
      description: 使用 Rainbond 2年，从云原生改造到生产环境运维，帮助团队完成运维模式转型。
    - title: 电信科学技术第五研究所
      logo: images/users/5suo.jpg
    - title: 联影医疗
      logo: https://www.united-imaging.com/assets/image/font_img/UIHC_whiteBG_CN_logo.svg
    - title: 武汉绿之云
      logo: https://cdn-store.goodrain.com/assets/images/lvzhiyun.png
    - title: 简帛信息科技有限公司
      logo: images/users/jianbo.jpg
    - title: 北京滴普科技有限公司
      logo: images/users/dipu.jpeg
    - title: 中海创科技
      logo: images/users/zhonghai.png
    - title: 山东鲁能软件
      logo: /images/users/luneng.png
    - title: 西南民族大学
      logo: /images/users/xinanmingzu.jpg
    - title: 广西体育高等专科学校
      logo: /images/users/guangxitizhuan.png
    - title: 清能互联
      logo: /images/users/qingnenghulian.png
    - title: 厦门吉联
      logo: /images/users/jilian.png
    - title: 江苏荣泽信息科技
      logo: /images/users/rongze.png
    - title: 青岛迪迪科技
      logo: /images/users/didi.png
    - title: 苏州不木网络科技有限公司
      logo: /images/users/bumu.png
    - title: 上海熙菱信息
      logo: /images/users/xiling.png
    - title: 上海勤和互联网技术软件开发有限公司
      logo: /images/users/qinghehulian.png
    - title: 福州众享家信息科技有限公司
      logo: /images/users/zhongxiangjia.png
    - title: 壹米滴答供应链集团有限公司
      logo: /images/users/yimidida.png
    - title: 四川万江港利水务有限公司
      logo: /images/users/wanjiang.png
    - title: 北京宏诚创新科技有限公司
      logo: https://www.honortrends.com/template/new-blue/img/logos/logo-blue.png
    - title: 苏美达集团
      logo: /images/users/sumeida.png
    - title: 拓维信息系统股份有限公司
      logo: https://www.talkweb.com.cn/static/img/logo.png
    - title: 北京胜顶智控科技有限公司
      logo: /images/users/sdzk.png
    - title: 北京金楼世纪科技有限公司
      logo: https://www.yuexin.cn/_nuxt/img/da3a284.png
    - title: 医家医健康
      logo: /images/users/yijiayi.png
outputs:
  home:
    - HTML
    - RSS
    - JSON
    - Algolia
outputFormats:
  Algolia:
    baseName: 'algolia'
    isPlainText: true
    mediaType: 'application/json'
    notAlternative: true
