project_id: '533480'
api_token: 'eca4eefe86a01c535e781cd77e318636eccc648571f93454fdd0c21be558ed46839e615ee800d799'
# api_token_env: CROWDIN_PERSONAL_TOKEN,
preserve_hierarchy: true
files:
  # docs markdown
  # - source: /docs/**/*
  #   translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
  # community markdown
  - source: /community/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs-community/current/**/%original_file_name%
  # case markdown
  - source: /case/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-blog-case/**/%original_file_name%
  # blog markdown
  - source: /blog/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-blog/**/%original_file_name%
  # usescene markdown
  - source: /case/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-blog-usescene/**/%original_file_name%