name: Rainbond Docs GitHub Actions
on:
  push:
    branches:    
      - 'main'
jobs:
  rainbond-docs-deploy:
    container: goodrainapps/alpine:3.7
    steps:
      - name: Trigger Rainbond build
        env: RAINBOND_SECRET
          RAINBOND_SECRET: ${{ secrets.RAINBOND_SECRET }}
          RAINBOND_API: ${{ secrets.RAINBOND_API }}
        run: |
          curl -d '{"secret_key":"$RAINBOND_SECRET"}' -H "Content-type: application/json" -X POST $RAINBOND_API